import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType, BorderStyle } from 'docx';
import { marked } from 'marked';

/**
 * Enhanced DOCX generator with Apple-level design standards
 */
class EnhancedDocxGenerator {
  constructor() {
    this.brandColors = {
      primary: '#86100E',      // Medical Red
      secondary: '#0B0F1A',     // Deep Blue-Black  
      accent: '#F43F5E',        // Bright Red
      muted: '#6B7280',        // Gray
      background: '#FAFAFA',     // Off-white
      foreground: '#374151'       // Dark gray
    };
    
    this.typography = {
      heading: {
        h1: { size: 48, bold: true, color: this.brandColors.primary },
        h2: { size: 36, bold: true, color: this.brandColors.secondary },
        h3: { size: 28, bold: true, color: this.brandColors.foreground },
        h4: { size: 22, bold: true, color: this.brandColors.foreground }
      },
      body: { size: 11, color: this.brandColors.foreground },
      caption: { size: 9, color: this.brandColors.muted, italics: true }
    };
  }

  /**
   * Convert Markdown to enhanced DOCX with beautiful formatting
   */
  async generateDocx(markdownContent, title) {
    const tokens = marked.lexer(markdownContent);
    const children = [];

    // Add title page
    children.push(...this.createTitlePage(title));

    // Process markdown tokens
    for (const token of tokens) {
      children.push(...this.processToken(token));
    }

    // Add footer
    children.push(...this.createFooter());

    const doc = new Document({
      sections: [{
        properties: {
          page: {
            margin: {
              top: 1440,    // 1 inch
              right: 1440,
              bottom: 1440,
              left: 1440
            },
            size: {
              orientation: 'portrait',
              width: 12240,  // 8.5 inches
              height: 15840   // 11 inches
            }
          }
        },
        children: children
      }]
    });

    return await Packer.toBuffer(doc);
  }

  /**
   * Create professional title page
   */
  createTitlePage(title) {
    return [
      // Title
      new Paragraph({
        children: [
          new TextRun({
            text: title,
            ...this.typography.heading.h1,
            color: this.brandColors.primary,
            size: 56
          })
        ],
        alignment: AlignmentType.CENTER,
        spacing: { after: 2400 } // 2 inches
      }),

      // Subtitle
      new Paragraph({
        children: [
          new TextRun({
            text: "Generated by iVisit Document Generator",
            ...this.typography.caption,
            size: 14
          })
        ],
        alignment: AlignmentType.CENTER,
        spacing: { after: 1200 } // 1 inch
      }),

      // Date
      new Paragraph({
        children: [
          new TextRun({
            text: new Date().toLocaleDateString('en-US', {
              year: 'numeric',
              month: 'long',
              day: 'numeric'
            }),
            ...this.typography.body,
            italics: true
          })
        ],
        alignment: AlignmentType.CENTER,
        spacing: { after: 2400 } // 2 inches
      }),

      // Page break
      new Paragraph({
        children: [],
        pageBreakBefore: true
      })
    ];
  }

  /**
   * Process markdown tokens and convert to DOCX elements
   */
  processToken(token) {
    switch (token.type) {
      case 'heading':
        return this.createHeading(token);
      case 'paragraph':
        return this.createParagraph(token);
      case 'list':
        return this.createList(token);
      case 'blockquote':
        return this.createBlockquote(token);
      case 'code':
        return this.createCodeBlock(token);
      case 'table':
        return this.createTable(token);
      case 'hr':
        return this.createHorizontalRule();
      default:
        return [];
    }
  }

  /**
   * Create styled heading
   */
  createHeading(token) {
    const level = token.depth;
    const style = this.typography.heading[`h${level}`];
    
    return [
      new Paragraph({
        children: [
          new TextRun({
            text: token.text,
            ...style,
            spacing: { before: 600, after: 400 } // 0.5 and 0.33 inches
          })
        ],
        heading: HeadingLevel[`HEADING_${level}`],
        spacing: { after: 800 }
      })
    ];
  }

  /**
   * Create styled paragraph
   */
  createParagraph(token) {
    const children = [];
    const text = token.text || '';
    
    // Process inline formatting
    if (token.tokens) {
      for (const inlineToken of token.tokens) {
        children.push(this.processInlineToken(inlineToken));
      }
    } else {
      children.push(
        new TextRun({
          text: text,
          ...this.typography.body,
          spacing: { line: 240 } // 1.2 line spacing
        })
      );
    }

    return [
      new Paragraph({
        children: children,
        spacing: { after: 200 }, // 0.17 inches
        indent: { left: 0 }
      })
    ];
  }

  /**
   * Process inline tokens (bold, italic, etc.)
   */
  processInlineToken(token) {
    const baseStyle = this.typography.body;
    
    if (token.type === 'strong' || token.type === 'bold') {
      return new TextRun({
        text: token.text,
        ...baseStyle,
        bold: true
      });
    }
    
    if (token.type === 'em' || token.type === 'italic') {
      return new TextRun({
        text: token.text,
        ...baseStyle,
        italics: true
      });
    }
    
    if (token.type === 'codespan') {
      return new TextRun({
        text: token.text,
        ...baseStyle,
        font: 'Courier New',
        size: 10,
        shading: {
          type: 'solid',
          color: 'F1F5F9' // Light blue background
        }
      });
    }

    return new TextRun({
      text: token.text,
      ...baseStyle
    });
  }

  /**
   * Create styled list
   */
  createList(token) {
    const items = [];
    
    for (const item of token.items) {
      const bullet = token.ordered ? `${item.index + 1}.` : '•';
      
      items.push(
        new Paragraph({
          children: [
            new TextRun({
              text: bullet,
              ...this.typography.body,
              bold: true,
              color: this.brandColors.primary
            }),
            new TextRun({
              text: ` ${item.text}`,
              ...this.typography.body
            })
          ],
          spacing: { after: 120 },
          indent: { left: 720 } // 0.5 inch indent
        })
      );
    }

    return items;
  }

  /**
   * Create styled blockquote
   */
  createBlockquote(token) {
    return [
      new Paragraph({
        children: [
          new TextRun({
            text: token.text,
            ...this.typography.body,
            italics: true,
            color: this.brandColors.muted
          })
        ],
        spacing: { after: 400 },
        indent: { left: 720 },
        border: {
          left: {
            color: this.brandColors.primary,
            size: 6,
            style: BorderStyle.SINGLE
          }
        }
      })
    ];
  }

  /**
   * Create styled code block
   */
  createCodeBlock(token) {
    return [
      new Paragraph({
        children: [
          new TextRun({
            text: token.text,
            font: 'Courier New',
            size: 10,
            color: 'FFFFFF'
          })
        ],
        shading: {
          type: 'solid',
          color: '1F2937' // Dark background
        },
        spacing: { after: 400 },
        indent: { left: 720 }
      })
    ];
  }

  /**
   * Create table from markdown table
   */
  createTable(token) {
    const rows = [];
    
    // Header row
    if (token.header && token.header.length > 0) {
      rows.push({
        children: token.header.map(cell => 
          new Paragraph({
            children: [
              new TextRun({
                text: cell,
                ...this.typography.body,
                bold: true,
                color: 'FFFFFF'
              })
            ],
            shading: {
              type: 'solid',
              color: this.brandColors.primary
            }
          })
        )
      });
    }

    // Data rows
    for (const row of token.rows) {
      rows.push({
        children: row.map(cell => 
          new Paragraph({
            children: [
              new TextRun({
                text: cell,
                ...this.typography.body
              })
            ]
          })
        )
      });
    }

    return [
      new Paragraph({
        children: [],
        spacing: { after: 400 }
      }),
      {
        type: 'table',
        rows: rows,
        width: {
          size: 100,
          type: 'pct'
        },
        borders: {
          top: { style: BorderStyle.SINGLE, color: this.brandColors.border },
          bottom: { style: BorderStyle.SINGLE, color: this.brandColors.border },
          left: { style: BorderStyle.SINGLE, color: this.brandColors.border },
          right: { style: BorderStyle.SINGLE, color: this.brandColors.border }
        }
      },
      new Paragraph({
        children: [],
        spacing: { after: 400 }
      })
    ];
  }

  /**
   * Create horizontal rule
   */
  createHorizontalRule() {
    return [
      new Paragraph({
        children: [],
        border: {
          bottom: {
            color: this.brandColors.primary,
            size: 3,
            style: BorderStyle.SINGLE
          }
        },
        spacing: { before: 400, after: 400 }
      })
    ];
  }

  /**
   * Create professional footer
   */
  createFooter() {
    return [
      new Paragraph({
        children: [],
        pageBreakBefore: true
      }),
      
      new Paragraph({
        children: [
          new TextRun({
            text: "Generated by iVisit Document Generator",
            ...this.typography.caption
          })
        ],
        alignment: AlignmentType.CENTER,
        spacing: { before: 1200 }
      }),

      new Paragraph({
        children: [
          new TextRun({
            text: "© 2026 iVisit. All rights reserved.",
            ...this.typography.caption
          })
        ],
        alignment: AlignmentType.CENTER
      })
    ];
  }
}

export default EnhancedDocxGenerator;
